### PR TITLE
Invasion Filter

### PR DESCRIPTION
**Pull request by Fabio1988**
split invasions to separate filter type, possibility to filter certain grunt types
also fixed filtering for pokestops, quests, invasions

## Motivation and Context

filter to only show favorite grunt types

## How Has This Been Tested?

successful tested for over 2 week now (2021-06-17)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Fabio1988** [comment]
I think those 2 are deprecated:
`CHARACTER_DARKNESS_GRUNT_FEMALE = 8
CHARACTER_DARKNESS_GRUNT_MALE = 9`

Ghost is now 47-48

**Comment by Fabio1988** [comment]
> I think those 2 are deprecated:
> `CHARACTER_DARKNESS_GRUNT_FEMALE = 8 CHARACTER_DARKNESS_GRUNT_MALE = 9`
> 
> Ghost is now 47-48

modified availableGrunts to remove some unused ones.

**Comment by Fabio1988** [comment]
has anyone else tested? works like a charm.

**Comment by feigei** [comment]
Works for fine for me. Would be nice to be able to resize the individual invasions, but it's not a must.

**Review by feigei — APPROVED** [review]
Works as intended. Individual invasion resizing would be a bonus, but not a must for me.


invasion
When you open invasion filter for the first time, the table headers are off, but once you sort by something it corrects itself.

**Pull request merged**
