### PR TITLE
V2_GAME_MASTER PVPStats

### PR DESCRIPTION
**Pull request by SkOODaT**
V2_GAME_MASTER PVPStats

## Description
Made pvpstats manager v2 compatible 

## Motivation and Context
Updates

## How Has This Been Tested?
Locally

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by 123FLO321** [comment]
@RealDeviceMap/testers please test

**Comment by SkOODaT** [comment]
ive been running it for over 24 hours now, thiers a few forms that error on start (2?), unreleased mons still but works fine other then that, stats look correct on the map... i dont pvp tho so if someone could test and verify data is correct :)

**Comment by kamieniarz** [comment]
Unfortunately I still have these errors so RDM isn't sending any webhooks with gen 6 PVP stats
```
[DBG]  [PVPStatsManager] Parsing game master V2 file
[WARN] [PVPStatsManager] Failed to get form for: SABLEYE_COSTUME_2020
[WARN] [PVPStatsManager] Failed to get pokemon for: CHESPIN
[WARN] [PVPStatsManager] Failed to get pokemon for: QUILLADIN
[WARN] [PVPStatsManager] Failed to get pokemon for: CHESNAUGHT
[WARN] [PVPStatsManager] Failed to get pokemon for: FENNEKIN
[WARN] [PVPStatsManager] Failed to get pokemon for: BRAIXEN
[WARN] [PVPStatsManager] Failed to get pokemon for: DELPHOX
[WARN] [PVPStatsManager] Failed to get pokemon for: FROAKIE
[WARN] [PVPStatsManager] Failed to get pokemon for: FROGADIER
[WARN] [PVPStatsManager] Failed to get pokemon for: GRENINJA
[WARN] [PVPStatsManager] Failed to get pokemon for: BUNNELBY
[WARN] [PVPStatsManager] Failed to get pokemon for: DIGGERSBY
[WARN] [PVPStatsManager] Failed to get pokemon for: FLETCHLING
[WARN] [PVPStatsManager] Failed to get pokemon for: FLETCHINDER
[WARN] [PVPStatsManager] Failed to get pokemon for: TALONFLAME
[WARN] [PVPStatsManager] Failed to get pokemon for: SCATTERBUG
[WARN] [PVPStatsManager] Failed to get pokemon for: SPEWPA
[WARN] [PVPStatsManager] Failed to get pokemon for: VIVILLON
[WARN] [PVPStatsManager] Failed to get pokemon for: LITLEO
[WARN] [PVPStatsManager] Failed to get pokemon for: PYROAR
[WARN] [PVPStatsManager] Failed to get pokemon for: PYROAR
[WARN] [PVPStatsManager] Failed to get pokemon for: PYROAR
[WARN] [PVPStatsManager] Failed to get pokemon for: FLABEBE
[WARN] [PVPStatsManager] Failed to get pokemon for: FLOETTE
[WARN] [PVPStatsManager] Failed to get pokemon for: FLORGES
[WARN] [PVPStatsManager] Failed to get pokemon for: SKIDDO
[WARN] [PVPStatsManager] Failed to get pokemon for: GOGOAT
[WARN] [PVPStatsManager] Failed to get pokemon for: PANCHAM
[WARN] [PVPStatsManager] Failed to get pokemon for: PANGORO
[WARN] [PVPStatsManager] Failed to get pokemon for: FURFROU
[WARN] [PVPStatsManager] Failed to get pokemon for: ESPURR
[WARN] [PVPStatsManager] Failed to get pokemon for: MEOWSTIC
[WARN] [PVPStatsManager] Failed to get pokemon for: MEOWSTIC
[WARN] [PVPStatsManager] Failed to get pokemon for: MEOWSTIC
[WARN] [PVPStatsManager] Failed to get pokemon for: SPRITZEE
[WARN] [PVPStatsManager] Failed to get pokemon for: AROMATISSE
[WARN] [PVPStatsManager] Failed to get pokemon for: SWIRLIX
[WARN] [PVPStatsManager] Failed to get pokemon for: SLURPUFF
[WARN] [PVPStatsManager] Failed to get pokemon for: INKAY
[WARN] [PVPStatsManager] Failed to get pokemon for: MALAMAR
[WARN] [PVPStatsManager] Failed to get pokemon for: BINACLE
[WARN] [PVPStatsManager] Failed to get pokemon for: BARBARACLE
[WARN] [PVPStatsManager] Failed to get pokemon for: SKRELP
[WARN] [PVPStatsManager] Failed to get pokemon for: DRAGALGE
[WARN] [PVPStatsManager] Failed to get pokemon for: CLAUNCHER
[WARN] [PVPStatsManager] Failed to get pokemon for: CLAWITZER
[WARN] [PVPStatsManager] Failed to get pokemon for: HELIOPTILE
[WARN] [PVPStatsManager] Failed to get pokemon for: HELIOLISK
[WARN] [PVPStatsManager] Failed to get pokemon for: TYRUNT
[WARN] [PVPStatsManager] Failed to get pokemon for: TYRANTRUM
[WARN] [PVPStatsManager] Failed to get pokemon for: AMAURA
[WARN] [PVPStatsManager] Failed to get pokemon for: AURORUS
[WARN] [PVPStatsManager] Failed to get pokemon for: SYLVEON
[WARN] [PVPStatsManager] Failed to get pokemon for: HAWLUCHA
[WARN] [PVPStatsManager] Failed to get pokemon for: DEDENNE
[WARN] [PVPStatsManager] Failed to get pokemon for: CARBINK
[WARN] [PVPStatsManager] Failed to get pokemon for: GOOMY
[WARN] [PVPStatsManager] Failed to get pokemon for: SLIGGOO
[WARN] [PVPStatsManager] Failed to get pokemon for: GOODRA
[WARN] [PVPStatsManager] Failed to get pokemon for: KLEFKI
[WARN] [PVPStatsManager] Failed to get pokemon for: PHANTUMP
[WARN] [PVPStatsManager] Failed to get pokemon for: TREVENANT
[WARN] [PVPStatsManager] Failed to get pokemon for: BERGMITE
[WARN] [PVPStatsManager] Failed to get pokemon for: AVALUGG
[WARN] [PVPStatsManager] Failed to get pokemon for: NOIBAT
[WARN] [PVPStatsManager] Failed to get pokemon for: NOIVERN
[WARN] [PVPStatsManager] Failed to get pokemon for: XERNEAS
[WARN] [PVPStatsManager] Failed to get pokemon for: YVELTAL
[WARN] [PVPStatsManager] Failed to get pokemon for: RUNERIGUS
[WARN] [PVPStatsManager] Failed to get pokemon for: RUNERIGUS
[WARN] [PVPStatsManager] Failed to get pokemon for: RUNERIGUS
[WARN] [PVPStatsManager] Failed to get pokemon for: RUNERIGUS
[DBG]  [PVPStatsManager] Done parsing game master file
```

**Comment by 123FLO321** [comment]
I rebased this PR from master and now includes 0.195.0 protos

**Review by 123FLO321 — APPROVED** [review]
changes look good to me.
Will merge once tests post-rebase test pass

**Pull request merged**
