### PR TITLE
Add Basic Option for A/B Quest Scans (with or without AR being kept in inventory)

### PR DESCRIPTION
**Pull request by kbtbc**
Adds a simple questType flag to send to client.

## Description
These changes are to direct the back-end client weather or not to keep or discard (or ignore) an AR type quest.   

## Motivation and Context
Currently we miss a lot of good quests for players since RDM only accommodates non-AR quest scans.   This adds an option to capture what is missing.

### CODE REVIEW

**Comment by 123FLO321** [comment]
replaced by #233

**Comment by 123FLO321** [comment]
reopening for now so people can use it untill #233 is merged

**Review by SkOODaT — APPROVED** [review]

**Comment by nappa85** [comment]
For the poor souls that's using docker builds, is it possible to make a container of that version?

**Comment by Fabio1988** [comment]
#233 is merged into development

**Pull request closed without merging**
