### PR TITLE
Update some packages to newer version

### PR DESCRIPTION
**Pull request by Fabio1988**
- turf-swift switched to main repo and updated (breaking change https://github.com/mapbox/turf-swift/pull/104/files) - needed fixes in RDM
- swift-backtrace updated
- Perfect-Crypto switched to main repo and updated

### CODE REVIEW

**Comment by Fabio1988** [comment]
@123FLO321 not all, because they do not provide any tags. an update on their side without any provided tags can lead to a break in RDM in the future. On some of them you updated the Package.swift to support newer SWIFT version.

I could review it again and try to point the git commit directly if possible, like that:

> // Depending on an exact commit:
.package(
    url: "https://github.com/johnsundell/files.git",
    .revision("0e0c6aca147add5d5750ecb7810837ef4fd10fc2")
)

**Comment by 123FLO321** [comment]
what repos are not updated yet?

**Comment by Fabio1988** [comment]
https://github.com/123FLO321/Perfect-Session-MySQL/tree/swift5

**Comment by Fabio1988** [comment]
most of the package.swift changes were to support swift 5, because they have dependencies to swift 4.... :(
see https://github.com/123FLO321/Perfect-LinuxBridge/commit/b6b29afcd3ca1147cf04382242ab5a5d734b8889

**Pull request merged**
