### PR TITLE
Cache s2 cells, instead of updating all the time

### PR DESCRIPTION
**Pull request by Fabio1988**

### CODE REVIEW

**Comment by Fabio1988** [comment]
@TurtIeSocks does RM refer to s2cell updated column? this PR will update the updated column only every hour instead of everytime

**Comment by TurtIeSocks** [comment]
@Fabio1988 yeah it does but if the performance benefits are there, then no need to maintain it for RM. I will just update the scale that determines the color.

**Comment by Fabio1988** [comment]
> @Fabio1988 yeah it does but if the performance benefits are there, then no need to maintain it for RM. I will just update the scale that determines the color.

In RDM too, have to update scale too I see 🤣

**Comment by jfberry** [comment]
I suspect you can go to 10 min (or even 5 min) and still get the main part of the improvement. Before you would have been updating many times a second

**Comment by TurtIeSocks** [comment]
Perhaps a configurable value that's saved to the meta table for RM to find 😊

**Comment by Fabio1988** [comment]
> Perhaps a configurable value that's saved to the meta table for RM to find blush

I would suggest the hard-coded part. I set it to 900 seconds / 15 minutes now... should be fine... Don't let the user to config too much things, then they complain ;) 

will merge today :)

**Pull request merged**
