### PR TITLE
Make disabling account after receiving an RPC 12 from MITM optional

### PR DESCRIPTION
**Pull request by DavisPoGo**
## Description
Adds a new option to docker-compose.yml (ACC_DISABLE_ON_UNK_ERROR) and local.json (disableOnUnkError) to provide the option to either disable the accounts when they receive an rpc code: 12 or not. The default setting is true to align with the way the rpc code: 12 is currently handled. By setting disableOnUnkError to false, accounts will not be disabled when they receive rpc code: 12. Encounter limit functionality has not been changed.

## Motivation and Context
My account were receiving rpc code: 12 from 1-5 times in a row causing them to be disabled. When I hand checked the accounts they did not have the maintenance screen. Since encounter limits made things stable, I wanted to have a way to run new versions of MITM with the encounter limit.

## How Has This Been Tested?
I built the image and tested on my local setup. I have already observed accounts receiving multiple rpc code 12, not logging out, and being able to function with the same account

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Fabio1988** [comment]
When not disabling on rpc 12, how do you handle account switch if it's a BSOD?

**Comment by DavisPoGo** [comment]
I scheduled a mysql query to look for phones that had been offline for a while based on a device monitoring table. Could probably just use last_seen instead but RDMMonitor device restarts result in that column getting updated. It was pretty infrequent when the encounter limiter wouldn't switch the account before BSOD

**Comment by Fabio1988** [comment]
I would probably go another way... Count the rpc12, and only disable after 5th or 10th time...

**Comment by DavisPoGo** [comment]
I think that idea is great. I'll see if I can figure out how to do that.

**Comment by Fabio1988** [comment]
You can reuse functionality of the encounter count. A dict of Username to rpc count

If it hits 5 times then mark disabled. We could also reset that count when valid data is incoming again, before we hit the limit :)

**Comment by DavisPoGo** [comment]
I'm going to close this because I created a new PR (512) that enables setting a custom RPC 12 limit before disabling account

**Pull request closed without merging**
