### PR TITLE
Add tile with Total over Level 40

### PR DESCRIPTION
**Pull request by lenisko**
## Description

Add a tile to include accounts with level over 40.
Moved `Failed Accounts` tile below to the warnings sections.

## Motivation and Context

We already store them in there, so why not keeping a track of how many in readable format?

## How Has This Been Tested?

Wasn't yet

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Fabio1988** [comment]
Over 40? You need to do quests on the account to reach 41 :)

**Comment by lenisko** [comment]
@Fabio1988 it's including from what I saw :)

```
    public static func getLevelCount(mysql: MySQL?=nil, level: Int) throws -> Int64 {

        ...

        let sql = """
            SELECT COUNT(*)
            FROM account
            WHERE level >= ?
        """
```

**Comment by Fabio1988** [comment]
so it's bit misleading I think. The count for over 30 would contain also the count of over 40... :confused:

**Comment by lenisko** [comment]
It's okay I think. I mean in the table we can see detailed information about how many accounts per level we have. In this case it's just used to tell us quickly that we have X accounts with 30 or more, and Y accounts with 40 or more.

**Pull request merged**
