### PR TITLE
Trainer XP from holo inventory with ability to save data in database

### PR DESCRIPTION
**Pull request by lenisko**
Extended version of https://github.com/RealDeviceMap/RealDeviceMap/pull/146 with ability to save total experience in database based on switch.

## Description
Added new switch for leveling instance to chose whatever we want to store total experience in database or not.

## Motivation and Context
Useful to track progress in monitoring tools.

## How Has This Been Tested?
Testing on own production. No problems from 4 days~

- ON/OFF database saving switch works okay and is not changeable on other instances than "Leveling" where it stays OFF.
- Query update times are low enough
- Status on instance page is updated correctly

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by lenisko** [comment]
Started testing on production. Updated `How Has This Been Tested?` section.

**Comment by Fabio1988** [comment]
worked as intended... :+1:

**Comment by Fabio1988** [comment]
@lenisko @123FLO321 
from this holo inventory protos, is it also possible to extract trainer name?

Leveling instances only show trainer-name with progress, never account-username

**Comment by lenisko** [comment]
> 
> 
> @lenisko @123FLO321
> from this holo inventory protos, is it also possible to extract trainer name?
> 
> Leveling instances only show trainer-name with progress, never account-username. So it's difficult to associate it from account table in DB.

Unsure, didn't checked. I would like to get it merged so lets focus on what we have for now, and expand later if needed :)

**Review by Fabio1988 — APPROVED** [review]

**Review by kbtbc — COMMENTED** [review]
Just started testing this.   Only running a few minutes -- do finally see stats in the dashboard 

Noticed two settings in Instance:
image
What does store 'Data' add? 

Also, regarding the note about displaying the username instead of the trainer name isn't `username` already a variable available (used in mysql query)?

Will check back to approve in a couple hours.

**Comment by Fabio1988** [comment]
"store data" is old setting which is available already. I think it would save quests or pokemon nearby. But no IV if the acc is below 30

**Comment by lenisko** [comment]
@kbtbc It's unrelated to change & just like @Fabio1988 mentioned.

**Review by kbtbc — APPROVED** [review]
Thanks for the clarification above. 

It works great at fixing the display, and the toggle to update the db also seems to work.   It's a great fix.   Approved!  ;p

Something else I would like to see added (perhaps also after a merge) is at "Lvl.30 done" the total time added to that dashboard info would be helpful.

**Review by 123FLO321 — COMMENTED** [review]
Whats the reason for storing XP in the database?

**Comment by lenisko** [comment]
@123FLO321 Metrics. It's optional and default off though. Back then I was using "cron like" script to pull this data using sql query to calculate approximate time needed to reach desired level.

**Comment by Fabio1988** [comment]
Merged with #146 ?

**Comment by 123FLO321** [comment]
> @123FLO321 Metrics. It's optional and default off though. Back then I was using "cron like" script to pull this data using sql query to calculate approximate time needed to reach desired level. Same does lorg.

@lenisko but all this info is available already via the API

**Comment by lenisko** [comment]
@123FLO321 You got me there :)

For those who tested this PR, it might be required to reset `DB_VERSION` to `69` before next migration.
Query: ```UPDATE `metadata` SET `value` = '69' WHERE `metadata`.`key` = 'DB_VERSION'; ```

Leaving for reference `/api/get_data?show_instances=true` with basic authorization.

```
...
{
      "type": "Leveling",
      "status": [{
        "xp_target": 2000000,
        "xp_percentage": 91.15325,
        "xp_start": 0,
        "xp_current": 1823065,
        "time_left": 0.14825220176744677,
        "level": 29,
        "username": "...",
        "xp_per_hour": 1193473
      }],
      "count": 1,
      "name": "..."
    }
...
```

**Pull request closed without merging**
