### PR TITLE
Merge Development to master

### PR DESCRIPTION
**Pull request by Fabio1988**
- Dual quest
- power-up Pokestops/Gyms
- Stats page (icons needed, e.g. [NilePlumb's PkmnShuffleMap Icons](https://github.com/nileplumb/PkmnShuffleMap/tree/master/RDM_ALL/misc)
- configurable webhooks (migration supports 10 webhooks, if you have more, then please create the missing ones on your own - MySQL 5.7 restricts it that way)
- new API features ([examples](https://github.com/RealDeviceMap/RealDeviceMap/pull/268))
- use global translation [repo](https://github.com/WatWowMap/pogo-translations) for Frontend
- enhanced PVP ranking calculation
- improve DB Migration Backup workflow
- Update PROTOS to 2.9 (229.0)
- Cache S2 Cell IDs for Bootstraping
- Update Weather each hour (even if weather hasn't changed)
- many more

### CODE REVIEW

**Review by jepke — COMMENTED** [review]
Develop works fine

**Review by jepke — DISMISSED** [review]

**Review by whitewillem — DISMISSED** [review]

**Review by samonthenetuk — APPROVED** [review]
Been using for a while and all working well with no bugs.

**Review by dapolli — APPROVED** [review]
Läuft alles stabil. Konnte bisher keine Bugs entdecken.

**Review by feigei — APPROVED** [review]
I have been testing development since it started. The additional features are nice and there are currently no issues at all to my knowledge.

**Comment by lenisko** [comment]
Using from the moment develop was added. All good & solid !

**Pull request merged**
