### PR TITLE
Custom Navbar Buttons

### PR DESCRIPTION
**Pull request by 123FLO321**
## Description
Adds settings to add custom navbar buttons 

## Motivation and Context
This allows admins to add custom buttons (e.g. for blogs, PayPal, etc.)

## How Has This Been Tested?
Tested locally on MacOS

## Screenshots (if appropriate):
image

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by whitewillem** [comment]
looks good. maybe we could use fontawesome to add fancy icons (?)

**Comment by 123FLO321** [comment]
@whitewillem you can add html as "name" not just text. So you can do whatever you want.

**Comment by 123FLO321** [comment]
Known issue: If no buttons are added setting page incorrectly fills „?;?“ into the button fields.

**Comment by 123FLO321** [comment]
@PapileinDE
> RealDeviceMap 0x000055cdde44759b static RealDeviceMap.Instance.getAll(mysql: Swift.Optional<PerfectMySQL.MySQL>) throws -> Swift.Array<RealDeviceMap.Instance> + 1787 at Instance.swift:157

Line 157 is:
> let type = InstanceType.fromString(result[1] as! String)!

This is likely not because of this PR but because you forgot to remove the leveling instance after switching PRs.
Can you confirm that?

**Comment by PapileinDE** [comment]
> @PapileinDE
> 
> > RealDeviceMap 0x000055cdde44759b static RealDeviceMap.Instance.getAll(mysql: Swift.Optional<PerfectMySQL.MySQL>) throws -> Swift.Array<RealDeviceMap.Instance> + 1787 at Instance.swift:157
> 
> Line 157 is:
> 
> > let type = InstanceType.fromString(result[1] as! String)!
> 
> This is likely not because of this PR but because you forgot to remove the leveling instance after switching PRs.
> Can you confirm that?

I can ... sorry my fault :(

**Comment by 123FLO321** [comment]
@PapileinDE No problem.

**Pull request merged**
