### PR TITLE
Rework Device Groups + Auto Assignmets

### LINKED ISSUE #134: [Feature Request] Instance done timestamp for quests in dashboard
**Describe the solution you'd like**
RDM writes Instance done in docker logs but why not add timestamp into a extra DB column so it can be shown in the instance overview page on the dashboard.

### LINKED ISSUE #135: [Feature Request] Chained auto assignments on complete & date/time assignments for events
**Describe the solution you'd like**
Currently we can have multiple fixed time assignments but only 1 oncomplete.
Example: I have 1 area i want to scan for quests 100% but i do have about 4 hours left untill 8am in the morning. I want to utilize those 4 hours to get some extra quests scanned. I can use a on complete to go to the secondary quest instance but that one only takes 2 hours so still 2 left. The time the second one finishes varies everyday so to make the most of every minute i would like to chain up multiple oncomplete triggers.

So if we can give a priority number to each on complete. If priority 1 is complete do 2 if 2 complete 3 and so on.

For date/time assignments this comes in place for events like community day or other specific events that are worth changing focus on what is scanned at that time.

### LINKED ISSUE #151: [Feature Request] Add Device Groups to Auto-Assignments
**Is your feature request related to a problem? Please describe.**
Add Device Groups to Auto Assignments for easier management of device assignments

**Describe the solution you'd like**
In the drop down for "Select Target Device" it should show two groups, one for groups and one for devices ex:

[Device Groups]
- All Devices
- Group 1

[Devices]
- Device 1
- Device 2
- Device 3

Optionally might want to add a delay field to provide a small delay in assigning the instances when a group is selected to not have all devices logout/in right away

**Describe alternatives you've considered**
Optionally or Additionally Assign Devices could be added to Instance pages to allow multi selecting devices to assign to an instance

**Additional context**
Just some thoughts to simplify management of devices

### PR DESCRIPTION
**Pull request by 123FLO321**
## Description
- Rework Device Groups:
  - Devices can now be in multiple Groups
  - Easier assigning of all devices to an Instance
- Auto Assignments
  - Add option to select entire Device Groups
  - Add option to chain Assignments (via Source Instance option)
  - Add option to run on a specific day only
- Show Completed Time for Quest Instances
- Show Processing Queue in /dashboard
- Show Uptime in /dashboard
- Clear and Rescan IVs on Weather-Boosted state change
- Save and Reload last updated timestamp for Auto Assignmets after restart/crash

## Motivation and Context
closes #151 
closes #134
close #135
related #75 (helps but doesn't quite solve it)

## How Has This Been Tested?
Some local testing but needs further testing.

## Screenshots:
image
image
image
image
image

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by auisgold** [comment]
Quest Instance show as completed when all stops have been attempted rather than when quest data has been obtained for all stops

**Comment by 123FLO321** [comment]
That’s indented behaviour.
Thats always been the case just never showed it visually that the auto complete got triggered.
It triggers once all quests got attempted 3 times.

**Comment by auisgold** [comment]
Crashes when trying to go from one on complete instance to another

**Comment by 123FLO321** [comment]
@auisgold logs pls

**Comment by auisgold** [comment]
This is all that's in logs when it crashes
image

**Comment by 123FLO321** [comment]
@auisgold Does the crash always happen when moving from one to another instance?
I see no indication of the crash beeing related to assignments.

**Comment by auisgold** [comment]
I only noticed crashes when going from one instance to another, haven't been able to reproduce it though as now none of my auto assignments trigger.

**Comment by auisgold** [comment]
No longer seeing a crash when going from one instance to another, however, chaining auto assignments still doesn't seem to trigger, quest instance will complete but not go on to the next one for a device group.

**Comment by 123FLO321** [comment]
@auisgold should be fixed now

**Pull request merged**
