### PR TITLE
Pokémon size doesn't refer static to size literals

### PR DESCRIPTION
**Pull request by Fabio1988**
removed method to visualize tiny, small, normal, large, big. Instead return right XL or XS values.

## Description
Pokémon doesn't have a static way to calculate if they are tiny, small, normal, large or big. This calculation should happen separately for each Pokémon species.
This should introduce right XL or XS labels into RDM. It's possible because all Base weight and height for each Pokémon are in GameMaster.json. Actually I use the PVPStatsManager Thread for requesting GameMaster stats for base height and weight.

## Motivation and Context
Not all Roggenrola and Pidgey are small, but with the old behaviour they are always tiny.

## How Has This Been Tested?
tested successful.

## Screenshots (if appropriate):
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by versx** [comment]
No offense to you or Flo, but... why even try with RDM map anymore when there are much better alternatives like PMSF?




















lol...

**Comment by Fabio1988** [comment]
Also fixed deprecation notices from Shell.swift....
Ready for testing, deployment was successful

**Comment by Fabio1988** [comment]
`2021-08-24T06:36:14.281110237Z 0x55627c78e410, RealDeviceMap.PVPStatsManager.getBaseAndWeightForPokemon(pokemon: POGOProtos.HoloPokemonId, form: Swift.Optional<POGOProtos.PokemonDisplayProto.Form>, gender: Swift.Optional<POGOProtos.PokemonDisplayProto.Gender>) -> (Swift.Double, Swift.Double) at /build/Sources/RealDeviceMap/Misc/PVPStatsManager.swift:276
2021-08-24T06:36:14.282199704Z 0x55627c7da7ba, RealDeviceMap.Pokemon.(setPVP in _DE3D1B69EB570DAFAE2CCE46D90B7A5D)() -> () at /build/Sources/RealDeviceMap/Modell/Pokemon.swift:471
2021-08-24T06:36:14.282210003Z 0x55627c7d9da4, RealDeviceMap.Pokemon.addEncounter(mysql: PerfectMySQL.MySQL, encounterData: POGOProtos.EncounterOutProto, username: Swift.Optional<Swift.String>) -> () at /build/Sources/RealDeviceMap/Modell/Pokemon.swift:417
2021-08-24T06:36:14.282825657Z 0x55627c8738d1, function signature specialization <Arg[1] = Value Promoted from Box, Arg[6] = Value Promoted from Box, Arg[13] = Value Promoted from Box> of closure #1 () -> () in static RealDeviceMap.WebHookRequestHandler.rawHandler(request: PerfectHTTP.HTTPRequest, response: PerfectHTTP.HTTPResponse, host: Swift.String) -> () at /build/Sources/RealDeviceMap/Webhook/WebHookRequestHandler.swift:691
2021-08-24T06:36:14.282837810Z 0x55627c87e0ac, partial apply forwarder for function signature specialization <Arg[1] = Value Promoted from Box, Arg[6] = Value Promoted from Box, Arg[13] = Value Promoted from Box> of closure #1 () -> () in static RealDeviceMap.WebHookRequestHandler.rawHandler(request: PerfectHTTP.HTTPRequest, response: PerfectHTTP.HTTPResponse, host: Swift.String) -> () at /build/<compiler-generated>:0
2021-08-24T06:36:14.283015789Z 0x55627c703110, reabstraction thunk helper from @escaping @callee_guaranteed () -> () to @escaping @callee_guaranteed () -> (@out ()) at /build/<compiler-generated>:0
2021-08-24T06:36:14.283024927Z 0x55627c703110, partial apply forwarder for reabstraction thunk helper from @escaping @callee_guaranteed () -> () to @escaping @callee_guaranteed () -> (@out ()) at /build/<compiler-generated>:0
2021-08-24T06:36:14.283028624Z 0x55627c703298
2021-08-24T06:36:14.283032551Z 0x55627c703150, reabstraction thunk helper from @escaping @callee_guaranteed () -> (@out ()) to @escaping @callee_guaranteed () -> () at /build/<compiler-generated>:0
2021-08-24T06:36:14.283037561Z 0x55627c703150, partial apply forwarder for reabstraction thunk helper from @escaping @callee_guaranteed () -> (@out ()) to @escaping @callee_guaranteed () -> () at /build/<compiler-generated>:0
2021-08-24T06:36:14.283055415Z 0x55627c6ffe7a, closure #1 () -> () in PerfectThread.Threading.(SerialQueue in _1D5A1E6BBADDE06CD6E920A7263E7F40).startLoop() -> () at /build/.build/checkouts/Perfect-Thread/Sources/PerfectThread/ThreadQueue.swift:113
2021-08-24T06:36:14.283065003Z 0x55627c701375, closure #1 (Swift.Optional<Swift.UnsafeMutableRawPointer>) -> Swift.Optional<Swift.UnsafeMutableRawPointer> in static PerfectThread.Threading.(dispatchOnNewThread in _1D5A1E6BBADDE06CD6E920A7263E7F40)(closure: () -> ()) -> () at /build/.build/checkouts/Perfect-Thread/Sources/PerfectThread/ThreadQueue.swift:273
2021-08-24T06:36:14.283071115Z 0x7f6a58b0c6da
2021-08-24T06:36:14.283568523Z 0x7f6a56057a3e
2021-08-24T06:36:14.283590605Z 0xffffffffffffffff
`

**Comment by Fabio1988** [comment]
actually they introduced `XXS` and `XXL` too...
Niantic removed Weight labels completely in v221, maybe a bug, maybe not....

for the new introduced labels it's possible that they used the 4th deviation. 2nd deviation for XL and XS, 4th for XXL and XXS

**Comment by Fabio1988** [comment]
removed "weight" label, due it's not existing anymore ingame

**Pull request merged**
