### PR TITLE
Smarter getNewAccount per instance

### LINKED ISSUE #77: [Backend Bug Report] Quest instance retrieving accounts that has reached spin limit.
**Describe the bug**
Quest instance failed to complete due to not able to retrieve correct account. There were plenty of accounts available but the instance kept on logging in on the accounts that reached the spin limit.

**To Reproduce**
Quest instance logging in and out on accounts that has reached its spin limit. looping between 2-3 same accounts that has reached spin limit and did not grab other fresh accounts. 

**Expected behavior**
Quest instance should try to retrieve accounts that has not reached the spin limit.

**System**
 - Running in docker: yes
 - Docker Engine Version: 19.03.8
 - Host OS:  Ubuntu 18.04
 - RDM Version 1.6.8

### PR DESCRIPTION
**Pull request by 123FLO321**
## Description
Smarter get new account and account valid functions on Instance basis:
- Raid ignores warning, cooldown and spins
- Pokemon ignore cooldown and spins
- Quest uses limit set in instance
- Re-use accounts after warning
- Re-use accounts after suspension (needs suspension vs ban detection in UIC/macless) 
- Re-use accounts for questing based on current location instead of always waiting for 2h

And some cleanup
also fixes #77 and #86 
replaces #79 and #80

## How Has This Been Tested?
No

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### Title
Smarter account usage on Instance basis
### Description
- Changed `get_account` action to adapt depending on assigned Instance
  - Raid ignores warning, cooldown and spins
  - Pokemon ignore cooldown and spins
  - Quest uses limit set in instance
- Re-use accounts after warning
- Re-use accounts after suspension (needs suspension vs ban detection in UIC/macless) 
- Re-use accounts for questing based on current location instead of always waiting 2 hours

### CODE REVIEW

**Comment by SkOODaT** [comment]
Would be nice to have this in conjunction with someway a device remembers the accounts it was using so we can maximize account burnout time before pulling a new ones/unnecessary ones,
I also noticed this AM a lv30 get banned, the account logged out fine but it was continuously re-choosing the same lv 30 account, and was not updating the database to reflect "banned" status, The lv30 Account previous status was GPR_WARNING

**Comment by axelp86** [comment]
Questing doesn't work properly. Devices keep signing in and out, this resulted in an IP ban for me yesterday.

**Comment by axelp86** [comment]
Same goes for levelling, signing out and in (over and over again)

**Comment by 123FLO321** [comment]
@axelp86 can you try updating to the latest commit and see if this sill happens.
And if it does can you check the RDM logs about `not valid for` debug messages?

**Comment by axelp86** [comment]
After the last update it works great now.

**Comment by axelp86** [comment]
Works perfectly now.

**Comment by ch1zzu** [comment]
overall working as expected. but would be good to know the total of usable accounts?

**Comment by kbtbc** [comment]
How does this know to re-use accounts after warning or suspension?
Does it wait the 7 (or 30 days) before reuse, and reset the account status automatically?
If you have a raid instance it will grab a GPR_RED_WARNING account anyway?

**Comment by maglat** [comment]
Using the PR since I started mapping again two weeks ago. Works great for me.

**Comment by auisgold** [comment]
Working well for me.

**Pull request merged**
