### PR TITLE
Add NO_DITTO_LIST_CHECK switch to ignore ditto list during check

### PR DESCRIPTION
**Pull request by lenisko**
## Description
Add ability to disable ditto list check using `NO_DITTO_LIST_CHECK` env variable

## Motivation and Context

Maybe we won't have to use that list anymore?
It's the same as using list of `range(1, max_pokemon_id+1)`

## How Has This Been Tested?

Wasn't

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by yw2theorycrafter — COMMENTED** [review]
LGTM

**Review by yw2theorycrafter — APPROVED** [review]
LGTM

**Comment by 123FLO321** [comment]
do we even need that check or is it save to just remove it?

**Comment by lenisko** [comment]
@123FLO321 Apparently we don't, but would be better to give it a test for some time. Hence idea with switch as non-breaking change.

**Comment by lenisko** [comment]
closing as there's https://github.com/RealDeviceMap/RealDeviceMap/pull/280

**Pull request closed without merging**
