### PR TITLE
Hacky change of accounts 'Other' label to 'Suspended'

### PR DESCRIPTION
**Pull request by kbtbc**
Also, changed the dashboard count to display only the number accounts that are *actively* in the suspended state. 

These are display changes only.

### CODE REVIEW

**Comment by Fabio1988** [comment]
is `others` always `suspended` or are there more states in your DB?
I see we also write `error_26`, but I assume that's UIC and very old

**Comment by kbtbc** [comment]
I've never seen `error_26` in my db before.   I don't think we use `GPR_BANNED` anymore, either.   

I just wanted to be able to glance and see how many accounts were actually in the 30-day suspension window.   A more complete solution might include adding two new columns 'InWarning' and 'InSuspension' and keep the total running count columns.

**Comment by Fabio1988** [comment]
> I've never seen `error_26` in my db before. I don't think we use `GPR_BANNED` anymore, either.
> 
> I just wanted to be able to glance and see how many accounts were actually in the 30-day suspension window. A more complete solution might include adding two new columns 'InWarning' and 'InSuspension' and keep the total running count columns.

would appreciate that change, feel free, you already found the right place to do so :)

**Comment by Fabio1988** [comment]
> I've never seen `error_26` in my db before. I don't think we use `GPR_BANNED` anymore, either.
> 
> I just wanted to be able to glance and see how many accounts were actually in the 30-day suspension window. A more complete solution might include adding two new columns 'InWarning' and 'InSuspension' and keep the total running count columns.
> 
> ... and yes, I think 'Other' is always and only 'suspended' these days.

we use `GPR_BANNED` in code(https://github.com/RealDeviceMap/RealDeviceMap/blob/development/Sources/RealDeviceMapLib/Modell/Account.swift#L142), but only from PROTOS directly... so no way to get there, because MITM does not send PROTO in that case :)

**Comment by kbtbc** [comment]
I can try lol ...    Is the 'Spin Limit' column still relative?  I never see it populate

**Comment by Fabio1988** [comment]
You might have not hit the spin limit of each day during questing/leveling?! :)

**Comment by kbtbc** [comment]
> You might have not hit the spin limit of each day during questing/leveling?! :)

Yes, I also think (for me) accounts get swapped out before any limit is reached during questing.

**Comment by kbtbc** [comment]
Updated with new columns.

**Comment by kbtbc** [comment]
image

**Pull request merged**
