### PR TITLE
Don't save Name if Name is null

### PR DESCRIPTION
**Pull request by 123FLO321**
## Description
- Don't save Gym and Pokestop Names if then Name is not known

## Motivation and Context
Prevents overriding scrapped names

## How Has This Been Tested?
Not tested.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Fabio1988** [comment]
What would happen if a new gym is found, or a pokestop converted to a gym, and RDM only receives position and picture without interacting with the gym? Or is this new fix only for update, not store?

**Review by kbtbc — DISMISSED** [review]
tested, seems to work as intended.  Scraped gym names correctly updated in database.

**Comment by Fabio1988** [comment]
@kbtbc also on next day, or is it null again?

**Comment by kbtbc** [comment]
I just discovered this error, not sure if it's related:
```realdevicemap | [ERR]  [POKESTOP] Failed to execute query. (Cannot add or update a child row: a foreign key constraint fails (`rdmdb`.`pokestop`, CONSTRAINT `fk_pokestop_cell_id` FOREIGN KEY (`cell_id`) REFERENCES `s2cell` (`id`) ON DELETE CASCADE ON UPDATE CASCADE))```

**Comment by tppkgo** [comment]
Yeah this PR does not work as intended. new stops and gyms are not added to the database. Had to revert to 173 and now they get added.

**Comment by 123FLO321** [comment]
@tppkgo @kbtbc should be fixed now

**Comment by tppkgo** [comment]
@123FLO321 Confirmed its working fine now! :) Thanks!

**Pull request merged**
