### PR TITLE
Small update to increase max instance name length

### PR DESCRIPTION
**Pull request by SenorKarlos**
## Description
Self Explaintory

## Motivation and Context
Names are long. Needed more chars

## How Has This Been Tested?
made changes to my own DB and used volumes to insert mustache files
edited and added names longer than 30 chars
nothing exploded

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Fabio1988** [comment]
do we really need a length of 255?
the index depends on that size too.. so better keep it smaller like 60 :)

**Comment by SenorKarlos** [comment]
Probably not, you'd have to explain more why that matters though 😅 couple points of RAM no?On Nov 22, 2022 12:50 p.m., Fabio1988 ***@***.***> wrote:
do we really need a length of 255?
the index depends on that size too.. so better keep it smaller like 60 :)

**Comment by jfberry** [comment]
I don’t think it’d use more ram or disk space as it’s a variable length column

**Comment by SenorKarlos** [comment]
Well set whatever you feel is best, I just went with a big number LOL On Nov 22, 2022 1:41 p.m., James Berry ***@***.***> wrote:

I don’t think it’d use more ram or disk space as it’s a variable length column

**Pull request closed without merging**
