### PR TITLE
stop abusing your worst accounts

### PR DESCRIPTION
**Pull request by plinytheelder**
title says it all

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Fabio1988** [comment]
https://github.com/RealDeviceMap/RealDeviceMap/issues/527

This should be really configurable :)

**Comment by fluffymcpuffy** [comment]
I like this, but then I am not an iPhone-scanner. I seems to have way less device downtime due to login limiter. 
Should we suffer for an inferior system? Although I can agree to configurable. I would think bans is a mite problem and not an RDM problem? Thin line anyways. 
So Y make it configurable pls?

**Comment by matt-yml** [comment]
> I like this, but then I am not an iPhone-scanner. I seem to have way less device downtime due to login limiter. Should we suffer for an inferior system? Although I can agree to configurable. I would think bans is a mitm problem and not an RDM problem? Thin line anyways. So Y make it configurable pls?

Been testing this for a few days and it cut my running disabled accounts from 9000 -> 2500. 
Will have to tune by adding more accounts to get the rate down to zero; that's my problem.

I'm running 100% on atv/atlas. No iOS scanning in my rig of 122x devices.

**Comment by madBeavis** [comment]
> Been testing this for a few days and it cut my running disabled accounts from 9000 -> 2500. Will have to tune by adding more accounts to get the rate down to zero; that's my problem.

not sure approaching an asymptote of zero is even doable.  we will always have to rest account accounts, i would just aim for steady over time.

been using sorted by asc sort for weeks now with 5k/48hrs for weeks now works well.  i did drop level portion of query.  

i see 3 options for config
1. current, desc
2. proposed, asc
3. random.  if someone desires randomness, they can have it also.  could be sort by just rand() or rand()*lastused to add some weighting.  perhaps i am giving the folks analyzing such things at pogo too much credit and a product of botting in ogame.

**Comment by matt-yml** [comment]
> been using sorted by asc sort for weeks now with 5k/48hrs for weeks now works well. i did drop level portion of query.

Datapoint: I'm running at 6000enc/60h. 

Agreed, steady (rate of zero) is a better goal. None will require excess resources.

**Pull request closed without merging**
