### PR TITLE
Use timezone instead of timezone offset in instances

### PR DESCRIPTION
**Pull request by Fabio1988**
list of available identifiers: https://gist.githubusercontent.com/mhijack/2b63b84d96802ccc719291474ac9df72/raw/fbd3f817339154060596d2a68cdea996fd2ac43e/time-zone-known-identifiers-complete-list.swift

### CODE REVIEW

**Comment by fluffymcpuffy** [comment]
I filled in timezone, when checking instance settings field is empty. this is confusing.
also why not make it a dropdown box to choose from?

(meanwhile reverted to develop)

**Comment by jfberry** [comment]
Why can you not just identify the timezone automatically?
Poracle has code for this, for example

**Comment by Fabio1988** [comment]
> I filled in timezone, when checking instance settings field is empty. this is confusing. also why not make it a dropdown box to choose from?
> 
> (meanwhile reverted to develop)

It's not working after some reports, thanks for testing... It seems that timezone is not created properly.

**Comment by Fabio1988** [comment]
> Why can you not just identify the timezone automatically? Poracle has code for this, for example

Because of:
- Swift Perfect
- CLLocation is not available somehow
- it's possible to obtain server TimeZone, but mapper need TimeZone regarding scanarea

I invested several hours to get valid timezones, lookups for coordinates... But it seems it's not possible with swift, at least not with the used perfect framework...

Using vapor framework would change a lot, but it's also a big effort to migrate to vapor (complete rewrite of RDM).

So I think there is no possibility within swift itself

**Pull request closed without merging**
