### PR TITLE
Webhook data control and blacklisting - credit: @versx

### PR DESCRIPTION
**Pull request by thunder123456**
Adds the option to control what data is sent to certain webhooks as well as provides a way to blacklist data for specific webhooks. Selecting multiple webhook types from the dropdown will present a filter box for each webhook type as well as a section to specify to only send data in a certain area to a specific webhook.

Currently Supports:

- Pokemon
- Raids (Hatched)
- Egg Levels
- Lure Modules
- Invasion Grunt Types
- Gym Teams
- Weather Conditions

Needs functionality and performance testing.
Migration:
```
CREATE TABLE IF NOT EXISTS `webhook` (
  `name` varchar(30) UNIQUE NOT NULL,
  `url` varchar(256) UNIQUE NOT NULL,
  `delay` double DEFAULT 5.0,
  `types` longtext,
  `data` longtext,
  `enabled` tinyint unsigned DEFAULT 1
);
```
Migration #2 (closed): (Converts old webhook urls, huge thanks to @hokiepokedad!)
```
SET @urls = (SELECT `value` FROM `metadata` WHERE `key` = 'WEBHOOK_URLS');

INSERT INTO `webhook` (
    `name`,
    `url`,
    `delay`,
    `types`,
    `data`,
    `enabled`
)
SELECT
    CONCAT('webhook_',
        ROW_NUMBER() OVER (
            ORDER BY url
        )
    ) AS `name`,
    `url` AS `url`,
    (
        SELECT
            `value`
        FROM 
            `metadata`
        WHERE
            `key`= 'WEBHOOK_DELAY'
    ) AS `delay`,
    '[]' AS `types`,
    '{}' AS `data`,
    1 AS `enabled`
FROM
    JSON_TABLE(CONCAT('["', REPLACE(@urls, ';', '", "'), '"]'), '$[*]' COLUMNS(url VARCHAR(100) PATH '$')) AS wh
```

### CODE REVIEW

**Comment by 123FLO321** [comment]
@thunder123456 Do you need help with this?

**Comment by thunder123456** [comment]
If you have time to fix the errors go for it

**Comment by maglat** [comment]
Is this one working?

**Comment by Swiss-Rainbow** [comment]
no is not possible 1 point missing files 2 point somewhere there is an error no data are coming out.

**Comment by maglat** [comment]
Sorry for asking again. I really would like to have this working. Is someone looking on this to make this work? Sadly my lack of skill wont help.

**Comment by Fabio1988** [comment]
#253

**Pull request closed without merging**
