### PR TITLE
Simple Pokestop Clustering for Questing

### PR DESCRIPTION
**Pull request by 123FLO321**
##  Description
- Add simple Pokestop clustering for questing
- Update Leveling (and Questing) cluster range from 40m to 80m temporarily

## Motivation and Context
This change assumes the usage of "Ultra Quest".

## How Has This Been Tested?
Not tested

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by auisgold** [comment]
Quests are slower using this PR. 7661 stop instance generally takes 3 hours to finish with 17 devices, but with this PR takes about 3 and a half hours.

**Comment by LordJavi** [comment]
Reduced time drastically, from 45-50m to 28m. 900 pokestops, 6 devices, GC.

**Comment by LordJavi** [comment]
Tested with #122 , no issues

**Comment by LordJavi** [comment]
Tested with low levels, no issues

**Comment by auisgold** [comment]
Tested after login loops were fixed and works as intended.

**Pull request merged**
