### PR TITLE
PVP Improvements (level caps, league filter, little league, ...)

### PR DESCRIPTION
**Pull request by Fabio1988**
## Description
- rework pvp structure in DB and webhook
- add selectable default rank like `dense`, `competition` and `ordinal` (dense is the old way how RDM calculated ranks) - more information https://en.m.wikipedia.org/wiki/Ranking
- league filter cap
- level caps
- little league support

## Explanation rank types
- dense = 1223 ranking -> used by RDM
- competition = 1224 ranking -> used by GoStadium and PokeGenie
- ordinal = 1234 ranking -> used by PoGoStat and Ohbem

## Default values for PVP calculation
- League filter: If the hundo in each level cap is under a certain cp value it won't be considered in PVP calculation. default for each league: `500: 450, 1500: 1400, 2500: 2350` 
- Level Cap: 50
- Rank Type: dense (old way how RDM processed Rank in the past)

## Motivation and Context
urgently required

## How Has This Been Tested?
Does work with RDM frontend...
Does work with PoracleJS
Does work with ReactMap latest `develop`
PMSF has pushed fixes to `develop`
WhMgr added PR to support that change

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by TurtIeSocks** [comment]
My 2c on this. Add a `pvp` column where you dump all 3 leagues like Chuck uses, instead of tacking on another league.

**Comment by Fabio1988** [comment]
> {
   "little":[
      {
         "competition_rank":null,
         "level":null,
         "cap":50,
         "dense_rank":null,
         "pokemon":453,
         "form":0,
         "percentage":null,
         "cp":null,
         "gender":1,
         "rank":null,
         "ordinal_rank":null
      },
      {
         "pokemon":454,
         "percentage":null,
         "cp":null,
         "cap":50,
         "form":0,
         "gender":1,
         "rank":null,
         "level":null,
         "ordinal_rank":null,
         "dense_rank":null,
         "competition_rank":null
      }
   ],
   "great":[
      {
         "level":50.0,
         "cp":937,
         "percentage":0.8359087725234109,
         "dense_rank":1067,
         "rank":1601,
         "form":0,
         "competition_rank":1601,
         "gender":1,
         "ordinal_rank":1602,
         "cap":50,
         "pokemon":453
      },
      {
         "rank":null,
         "percentage":null,
         "level":null,
         "gender":1,
         "dense_rank":null,
         "form":0,
         "competition_rank":null,
         "pokemon":454,
         "ordinal_rank":null,
         "cp":null,
         "cap":50
      }
   ],
   "ultra":[
      {
         "level":50.0,
         "cp":937,
         "pokemon":453,
         "cap":50,
         "form":0,
         "competition_rank":1601,
         "gender":1,
         "percentage":0.8359087725234109,
         "dense_rank":1067,
         "rank":1601,
         "ordinal_rank":1602
      },
      {
         "percentage":0.9857420418061675,
         "competition_rank":142,
         "ordinal_rank":142,
         "gender":1,
         "cp":2496,
         "form":0,
         "level":47.0,
         "dense_rank":129,
         "pokemon":454,
         "rank":142,
         "cap":50
      }
   ]
}

**Comment by jfberry** [comment]
Which rank type goes into 'rank' ? This is the only one that poracle uses currently
(aside from that question I think this will work out of the box for poracle, as this visually looks compatible with chuck)

**Comment by Fabio1988** [comment]
> Which rank type goes into 'rank' ? This is the only one that poracle uses currently (aside from that question I think this will work out of the box for poracle, as this visually looks compatible with chuck)

Admin can choose now, which rank is stored in rank key :)

**Comment by jfberry** [comment]
Superb, I would be pleased if an RDM user can test with poracle and let me know if any issues (from this description I predict it will just work but I would prefer to know before it is merged!)

**Comment by Fabio1988** [comment]
> Superb, I would be pleased if an RDM user can test with poracle and let me know if any issues (from this description I predict it will just work but I would prefer to know before it is merged!)

Will test soon, only have to restart Poracle without pvp internal config:)

**Comment by TurtIeSocks** [comment]
> @jfberry @TurtIeSocks does Poracle or ReactMap use e.g. `pvp.little.value`, RDM does not save `value` in DB, it only sorts the ranking regarding the value and ignores it later. Ohbem includes the `value` key in the result, therefore I am asking if it's unused in other tools or not :)

Unused by ReactMap.

**Comment by jfberry** [comment]
> @jfberry @TurtIeSocks
> does Poracle or ReactMap use e.g. `pvp.little.value`, RDM does not save `value` in DB, it only sorts the ranking regarding the value and ignores it later. Ohbem includes the `value` key in the result, therefore I am asking if it's unused in other tools or not :)

Unused by poracle

**Comment by jfberry** [comment]
Poracle users testing this should apply https://github.com/KartulUdus/PoracleJS/pull/697

**Comment by versx** [comment]
Damn, merged while I was on vacation in Mexico. 😅

**Comment by Mygod** [comment]
Pretty sure Ohbem uses 1224 ranking

Source: I wrote Ohbem

**Pull request merged**
