### PR TITLE
Temporarily Stop Using Warned Accounts, Combine Performance/Improvement PRs

### PR DESCRIPTION
**Pull request by kbtbc**
Stops RDM from using warned accounts in quest & raid instances.  See #132  This is done by setting `ignoringWarning: false` in those instances.

Additionally, this PR combines a few of the simple performance enhancement PRs into a single PR:  Includes PRs  #113 & #115 & #125 -- allowing the user to test multiple semi-approved open PRs at once.  

This PR is meant to be temporary a help until full solutions/merges are completed. 

Non-breaking, no db modifications.

### CODE REVIEW

**Comment by maglat** [comment]
using this some days now. no issues for me so far.

**Comment by nileplumb** [comment]
Switched to this yesterday, quests actually finished for me finally

**Comment by nileplumb** [comment]
Alas today it's back to its old issues and had current through hundreds of accounts

**Comment by 123FLO321** [comment]
Closing since all related  PRs are merged.

**Pull request closed without merging**
