### PR TITLE
Leveling Instance, Async Instance Start 

### PR DESCRIPTION
**Pull request by 123FLO321**
## Description
- Add Leveling Instance
- Start Instances in background thread = faster starting

## Motivation and Context
Levling ;)

## How Has This Been Tested?
Tested locally on MacOS

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by LordJavi** [comment]
Quest instances are broken, I can’t create a new one or edit existing

**Comment by 123FLO321** [comment]
Quest instances are fixed now.

**Comment by Gladiator10864** [comment]
Been running for 10 days now without issue. Ubuntu 18.04 docker-compose

**Comment by SkOODaT** [comment]
im having issues with the leveling instance it seems to work fine for several hours but eventually i either get a run away SQL connection issue that only happens on the leveling branch or the workers will just stop spinning and sit at a pokestop, a re-save of the instance is the only thing that gets them moving again, 
how many workers have everyone tested with?

**Comment by PapileinDE** [comment]
I tested with 2 workers ... no issues.

**Comment by 123FLO321** [comment]
Can you also report what 0-30 times you get?

**Comment by PoGoJoshS** [comment]
Has anyone else had the issue of quest instances running a lot slower with this pr? My quest instances were only 1/3 complete by the time they usually finish. After switching back to master they are completed in the usual amount of time. Haven't had time to look into it deeper yet due to work.

**Comment by PoGoJoshS** [comment]
When I tested the leveling prs quest instances were only 1/3 complete by the time they usually finish. After switching back to master they are completed in the usual amount of time. Haven't had time to look into it deeper yet due to work. But, I wanted to mention it right away before it possibly gets merged

**Comment by bradders2000** [comment]
In Cooldown.encounter, I believe there's an issue with your logic whereby it totally ignores any distance related cooldown required if the previous encounter took place before it was meant to (often the case with UQ).


            if lastTime == nil || lastTime! > now {
                encounterTime = now
            } else {
                let encounterTimeT = lastTime! + encounterCooldown(distM: distance)
                if encounterTimeT < now {
                    encounterTime = now
                } else {
                    encounterTime = encounterTimeT
                }
                if encounterTime - now >= 7200 {
                    encounterTime = now + 7200
                }
            }

should be...

            if lastTime! > now {
                lastTime = now
            }
            let encounterTimeT = lastTime! + encounterCooldown(distM: distance)
            if encounterTimeT < now {
                encounterTime = now
            } else {
                encounterTime = encounterTimeT
            }
            if encounterTime - now >= 7200 {
                encounterTime = now + 7200
            }

**Pull request merged**
