### PR TITLE
Fix Weather not saving

### LINKED ISSUE #148: [Backend Bug Report] Weather condition not updated
**Describe the bug**
Weather condition is not updated.

**To Reproduce**
1. Check an existing cell's weather
2. Go there, scan weather
3. It does not get updated

**Expected behavior**
Weather condition to be updated

**Screenshots**
None, but can arrange if needed

**System**
 - Running in docker: yes
 - Docker Engine Version: unknown
 - Host OS: ubuntu 18
 - RDM Version master, as of 2020-07-07

**Additional context**
None

### PR DESCRIPTION
**Pull request by 123FLO321**
## Description
- Fix weather no longer updating 

## Motivation and Context
Fixes #148 

## How Has This Been Tested?
Not tested

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Pogodenhelder** [comment]
This crashes RDM when starting with following result
``
[DBG]  [WebHookRequestHandler] [denhelder6] Sending task: scan_pokemon at 52.9320329572751,4.77953216120386
*** Error in `./RealDeviceMap': double free or corruption (!prev): 0x00007f707c002fa0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f71750db7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f71750e437a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f71750e853c]
./RealDeviceMap(+0x5c055c)[0x55cd7130355c]
./RealDeviceMap(+0x5c02da)[0x55cd713032da]
./RealDeviceMap(+0x5c0631)[0x55cd71303631]
/swift-4.1-RELEASE-ubuntu16.04/usr/lib/swift/linux/libswiftCore.so(+0x39f88b)[0x7f717828c88b]
./RealDeviceMap(+0x204700c)[0x55cd72d8a00c]
./RealDeviceMap(+0x214e6d1)[0x55cd72e916d1]
./RealDeviceMap(+0x21649a4)[0x55cd72ea79a4]
./RealDeviceMap(+0x66a62c)[0x55cd713ad62c]
./RealDeviceMap(+0x66eb71)[0x55cd713b1b71]
./RealDeviceMap(+0x487997)[0x55cd711ca997]
./RealDeviceMap(+0x66eab1)[0x55cd713b1ab1]
./RealDeviceMap(+0x66ad4c)[0x55cd713add4c]
./RealDeviceMap(+0x66e9fc)[0x55cd713b19fc]
./RealDeviceMap(+0x66e45e)[0x55cd713b145e]
./RealDeviceMap(+0x66e4d9)[0x55cd713b14d9]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f71771b66ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f717516b41d]
======= Memory map: ========
55cd70d43000-55cd739e4000 r-xp 00000000 fd:00 265828                     /app/RealDeviceMap
55cd739e5000-55cd73af7000 r--p 02ca1000 fd:00 265828                     /app/RealDeviceMap
55cd73af7000-55cd73ba5000 rw-p 02db3000 fd:00 265828                     /app/RealDeviceMap
55cd73ba5000-55cd73be3000 rw-p 00000000 00:00 0 
55cd748fb000-55cd74b81000 rw-p 00000000 00:00 0                          [heap]
``

**Comment by Pogodenhelder** [comment]
it seems after running it did update 1 time, so in the database its updated, since i reverted back to master it works again, but it doesnt update ( obviously )

Schermafbeelding 2020-07-08 om 22 53 05

**Comment by 123FLO321** [comment]
@Pogodenhelder Resolved

**Comment by Pogodenhelder** [comment]
retested and it works again!!1, thanks flo!

**Comment by svenberg** [comment]
Works for me!

**Pull request merged**
