### PR TITLE
Add Account Group + Event Mode + Fixes

### LINKED ISSUE #164: Can you add id to debug log entry when clearing iv for weather boost change?
https://github.com/RealDeviceMap/RealDeviceMap/blob/af116d8508b690e9d92f100d615583fe6ce6e0af/Sources/RealDeviceMap/Modell/Pokemon.swift#L672

`Log.debug(message: "[POKEMON] \(id) Weather-Boosted state changed. Clearing IVs")`

### PR DESCRIPTION
**Pull request by 123FLO321**
## Description
- Only use accounts with the same Account Group for an instance
- Store is_event if an Instances has 'Is Unique Event' in addition (will have both event and none event in the db)
- Use IV values of none event Pokemon (if allowed by weather)
- Fixes Quest WebHooks not sending
- Fix more Login Loops
- Add an option to change Gym and Pokestop names in the Frontend for Admins
- More misc fixes

## How Has This Been Tested?
Needs Testing

## Closes
#164 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by imArize** [comment]
I have been running this since gofest without any issues

**Comment by germanocaumo** [comment]
Does this PR also update pokemon if it changes to another species? Like in GoFest with habitats spawns changed every hour but RDM would not update the already scanned ones.
If not would it be possible to add?

**Comment by whitewillem** [comment]
Could conflicts be fixed and updated to latest master for make up day? Event starts at 11:00 local time

**Comment by 123FLO321** [comment]
@whitewillem done but untested

**Comment by unseenmagik** [comment]
image
I have been running this PR for a while and it has been issue/error free. Fix's some of the broken elements from master also. 
Thanks....

**Comment by LordJavi** [comment]
Running this PR since gofest. Works as expected

**Review by Fabio1988 — APPROVED** [review]

**Pull request merged**
