### PR TITLE
partner_id Tracking for Pokestop and Gym

### PR DESCRIPTION
**Pull request by bushe**
partner_id Tracking for Pokestop and Gym to be able to determine which Stops/Gyms are sponsored

## Description
- Adding partner_id tracking to Pokestop and Gym modells
- New migration to add partner_id to pokestop and gym tables
- Updated Submission cells to not use sponsor_id (not currently in use in PoGo) to partner_id

## Motivation and Context
More accurate usage of Submission cells that contain sponsored stops/gyms

## How Has This Been Tested?
Tested locally with docker image built on Ubuntu host

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by 123FLO321** [comment]
If sponsor id is no longer used wouldn’t it be easier to store partner_id in the sponsor_id column?

**Comment by bushe** [comment]
> So ingame PartnerID replaces SponsorID right?
> If sponsor id is no longer used wouldn’t it be easier to store partner_id in the sponsor_id column?

As far as I know SponsorID has never been used (at least I don't see any record of it being recorded in my db). I was leaving SponsorID there for future purpose in case it is enabled/used at some point.

It will still require a migration regardless if we store it in PartnerID or SponsorID, PartnerID is string of number but it is larger than the current smallint that the SponsorID is in the database

**Comment by 123FLO321** [comment]
I'd still recommend just replacing what value get's set as sponsor id instead of adding a new column.
Saves us a migration and doesn't break stuff then.

**Comment by Fabio1988** [comment]
#267

**Pull request closed without merging**
